CREATE TABLE `users_table` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`title` text NOT NULL,
	`description` text NOT NULL,
	`login` text NOT NULL,
	`github_id` integer NOT NULL,
	`gravatar` integer NOT NULL,
	`site_admin` integer NOT NULL,
	`name` text,
	`company_name` text,
	`location` text,
	`hireable` integer,
	`twitter_username` text,
	`public_repo_count` integer NOT NULL,
	`public_gist_count` integer NOT NULL,
	`followers_count` integer NOT NULL,
	`following_count` integer NOT NULL,
	`github_created_at` text NOT NULL,
	`github_updated_at` text NOT NULL,
	`total_private_repo_count` integer NOT NULL,
	`owned_private_repo_count` integer NOT NULL,
	`private_gist_count` integer NOT NULL,
	`disk_usage_count` integer NOT NULL,
	`collaborators_count` integer NOT NULL,
	`two_factor_enabled` integer NOT NULL,
	`plan_name` text NOT NULL,
	`plan_ldap_dn` text NOT NULL,
	`plan_business_plus` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `users_table_github_id_unique` ON `users_table` (`github_id`);